// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvqQcIhRxDbDaKIqDBsQM1Fn-Zj61xTn4',
    appId: '1:1006306144831:web:f0f56dcc37957a669abe8a',
    messagingSenderId: '1006306144831',
    projectId: 'flutter-remote-config-de-61bb8',
    authDomain: 'flutter-remote-config-de-61bb8.firebaseapp.com',
    storageBucket: 'flutter-remote-config-de-61bb8.firebasestorage.app',
    measurementId: 'G-E0YRRZKZ2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXIoJezGWRv1NVb8DV0kZ8ynyK40Ja-IA',
    appId: '1:1006306144831:android:e45c2aeaa72a8bfc9abe8a',
    messagingSenderId: '1006306144831',
    projectId: 'flutter-remote-config-de-61bb8',
    storageBucket: 'flutter-remote-config-de-61bb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6bM5avazAsmRlAQERTVcCckNfsUh5Gqo',
    appId: '1:1006306144831:ios:10a2df0a4eee61db9abe8a',
    messagingSenderId: '1006306144831',
    projectId: 'flutter-remote-config-de-61bb8',
    storageBucket: 'flutter-remote-config-de-61bb8.firebasestorage.app',
    iosBundleId: 'com.zwethuraaung.flutterremoteconfigdemo.flutterRemoteConfigDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6bM5avazAsmRlAQERTVcCckNfsUh5Gqo',
    appId: '1:1006306144831:ios:10a2df0a4eee61db9abe8a',
    messagingSenderId: '1006306144831',
    projectId: 'flutter-remote-config-de-61bb8',
    storageBucket: 'flutter-remote-config-de-61bb8.firebasestorage.app',
    iosBundleId: 'com.zwethuraaung.flutterremoteconfigdemo.flutterRemoteConfigDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvqQcIhRxDbDaKIqDBsQM1Fn-Zj61xTn4',
    appId: '1:1006306144831:web:3731f1fbdaeac40a9abe8a',
    messagingSenderId: '1006306144831',
    projectId: 'flutter-remote-config-de-61bb8',
    authDomain: 'flutter-remote-config-de-61bb8.firebaseapp.com',
    storageBucket: 'flutter-remote-config-de-61bb8.firebasestorage.app',
    measurementId: 'G-VN4LM42HSF',
  );

}